/*jshint esversion: 6 */
/*
################################
# WELCOME TO MUSE on Messenger #
################################
*/

const request = require('request');

const config = require('./config.json');
const youtube = require('./youtube.js');



/*
* Simple text message
*/
function replyMessage(recipientID, messageText) {
	return new Promise(function(resolve, reject) {
		const messageData = {
			recipient: {
				id: recipientID,
			},
			message: {
				text: messageText,
			},
		};

		callSendAPI(messageData)
	});
}

/*
* Send a button
*/
function replyButton(recipientID, option) {
	const messageData = {
		recipient: {
			id: recipientID, 
		},
		message: {
			attachment: {
				type: 'template',
				payload: {
					template_type: 'generic',
					elements: [{
						title: option.title,
						subtitle: "Generated by Muse4U bot",
                        item_url: option.mainUrl,
                        image_url: option.imageUrl,
						buttons: [{
							type: option.buttonType,
							url: option.buttonUrl,
							title: option.buttonTitle
						}],
					}],
				},
			},
		},
	};

	callSendAPI(messageData);
}

function replyAudio(recipientID, audioUrl) {
    const messageData = {
        recipient: {
            id: recipientID,
        },
        message: {
            attachment: {
                type: 'file',
                payload: {
                	url: audioUrl,
                },
            },
        },
    };

    callSendAPI(messageData, true);
}
/*
###############
# callSendAPI #
################
*/  
//Call the SEND API
function callSendAPI(messageData, isAttachment=false) {
	url = null;
	if (isAttachment){
		url = 'https://graph.facebook.com/v2.6/me/message_attachments';
	}
	else {
		url = 'https://graph.facebook.com/v2.6/me/messages';
	}
  request({
    uri: url,
    qs: { access_token: config.facebook.pageAccessToken},
    method: 'POST',
    json: messageData

  }, function (error, response, body) {
    if (!error && response.statusCode === 200) {
      const recipientId = body.recipient_id;
      const messageId = body.message_id;

      console.log("Successfully sent message with id %s to recipient %s",
        messageId, recipientId);
    } else if (response.statusCode !== 200) {
      console.error("Unable to send message. the response status is %s. Check the error details below...", response.statusCode);
      console.error(body);
    }

    else {
      console.error("Unable to send message due to an unknown issue");
      console.error(error);
    }
  });  
}


/*
	Call the Facebook API to send a message
*/
function sendMessage(messageData) {
	return new Promise(function(resolve, reject) {
		request({
			uri: 'https://graph.facebook.com/v2.6/me/messages',
			qs: { acces_token: config.facebook.pageAccessToken},
			method: 'POST',
			json: messageData,
		}, function(error, response, body) {
			if(!error && response.statusCode === 200) {
				console.log('Message sent!!');
				resolve();
			}
			else if (error) {
				reject(error);
			}
			else {
				reject(body.error);
			}
		});
	});
}


module.exports = {
	replyMessage,
	replyButton,
	replyAudio
};

youtube.searchSong("MHD bébé", function(results) {
	cyriac_id = "1289358267826971";

	replyAudio(cyriac_id, results.streamUrl)
    console.log(results);
});

